Update sycamore, with errors
Using the current version of sycamore, building the dependency
causes this strange error about JsCast not being in scope.

```

   Compiling sycamore v0.9.0-beta.2 (http://github.com/sycamore-rs/sycamore#16acf8eb)
error[E0599]: no method named `unchecked_ref` found for reference `&JsValue` in the current scope
  --> ~/.cargo/git/checkouts/sycamore-c13e2e94d3a8109f/16acf8e/packages/sycamore/src/motion.rs:43:69

   |
43 |                         f.borrow().as_ref().unwrap_throw().as_ref().unchecked_ref(),
   |                                                                     ^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
3  + use wasm_bindgen::JsCast;
   |
help: there is a method with a similar name
   |
43 |                         f.borrow().as_ref().unwrap_throw().as_ref().checked_div(),
   |                                                                     ~~~~~~~~~~~

error[E0599]: no method named `unchecked_ref` found for reference `&JsValue` in the current scope
  --> ~/.cargo/git/checkouts/sycamore-c13e2e94d3a8109f/16acf8e/packages/sycamore/src/motion.rs:54:69
   |
54 |                         g.borrow().as_ref().unwrap_throw().as_ref().unchecked_ref(),
   |                                                                     ^^^^^^^^^^^^^
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
3  + use wasm_bindgen::JsCast;
   |
help: there is a method with a similar name
   |
54 |                         g.borrow().as_ref().unwrap_throw().as_ref().checked_div(),
   |                                                                     ~~~~~~~~~~~

```